


hostname: leaf3
build_dir: ../temp/dellos10


dellos_system: 
    hostname: leaf3
 

dellos_interface:
   ethernet 1/1/1:
      desc: "Connected to spine1"
      switchport: False
      admin: up
      ip_and_mask: 172.16.0.5/31
   ethernet 1/1/2:
      desc: "Connected to spine2"
      switchport: False
      admin: up
      ip_and_mask: 172.16.0.11/31
   loopback 0:
      ip_and_mask: 10.0.0.5/32
 
   virtual-network 1700:
      vrf: DEV
      desc: "virtual-network interface"
      ip_and_mask: "10.70.10.3/24"
#      virtual_gateway_ip: "10.70.10.3"
      admin: up
 
   virtual-network 1800:
      vrf: DEV
      desc: "virtual-network interface"
      ip_and_mask: "10.80.10.3/24"
#      virtual_gateway_ip: "10.80.10.3"
      admin: up
 
   virtual-network 1900:
      vrf: DEV
      desc: "virtual-network interface"
      ip_and_mask: "10.90.10.3/24"
#      virtual_gateway_ip: "10.90.10.3"
      admin: up



dellos_bgp:
##    state: absent
    asn: 13
    router_id: 10.0.0.5
    neighbor:
 
      - ip: 172.16.0.4
        type: ipv4
        remote_asn: 10
        timer: 3 9
        adv_interval: 40
        fall_over: present
        default_originate: False
        sender_loop_detect: false
        admin: up
        state: present
#============================================================
      - ip: 10.0.0.1
        type: ipv4
        remote_asn: 10
        timer: 3 9
        adv_interval: 40
        fall_over: present
        default_originate: False
        sender_loop_detect: false
        src_loopback: 0
        src_loopback_state: present
        send_community:
           - type: extended
           - state: present
        address_family: 
           - type: ipv4
             activate: false
           - type: l2vpn
             activate: true
        admin: up
        state: present
 
      - ip: 172.16.0.10
        type: ipv4
        remote_asn: 10
        timer: 3 9
        adv_interval: 40
        fall_over: present
        default_originate: False
        sender_loop_detect: false
        admin: up
        state: present
#============================================================
      - ip: 10.0.0.2
        type: ipv4
        remote_asn: 10
        timer: 3 9
        adv_interval: 40
        fall_over: present
        default_originate: False
        sender_loop_detect: false
        src_loopback: 0
        src_loopback_state: present
        send_community:
           - type: extended
           - state: present
        address_family: 
           - type: ipv4
             activate: false
           - type: l2vpn
             activate: true
        admin: up
        state: present
     
    redistribute:
      - route_type: connected
        address_type: ipv4
        state: present

dellos_vlan:
    
    vlan 1700:
      description: "VNI1700"
      untagged_members:
        - port: ethernet 1/1/3
          state: present
      state: present
    
    vlan 1800:
      description: "VNI1800"
      untagged_members:
        - port: ethernet 1/1/4
          state: present
      state: present
    
    vlan 1900:
      description: "VNI1900"
      untagged_members:
        - port: ethernet 1/1/5
          state: present
      state: present
     
  
dellos_vxlan:
    anycast_gateway_mac: "00:22:33:44:55:33"
    loopback:
      loopback_id: 10
      description: "HARDWARE_VXLAN"
      ip_address: "10.10.0.5/32"
      state: "present"
    nve:
      source_interface: 0
      state: "present"
    rmac: 00:11:11:11:11:11
    evpn:
      autoevi: False
      evi:
    
        - id: 1700
          rd: 10.0.0.5:1700
          vni:
            id: 1700
            state: "present"
          route_target:
            - type: "manual"
              asn_value: "1700:1700"
              route_target_type: "both"
              state: "present"
          state: "present"
    
        - id: 1800
          rd: 10.0.0.5:1800
          vni:
            id: 1800
            state: "present"
          route_target:
            - type: "manual"
              asn_value: "1800:1800"
              route_target_type: "both"
              state: "present"
          state: "present"
    
        - id: 1900
          rd: 10.0.0.5:1900
          vni:
            id: 1900
            state: "present"
          route_target:
            - type: "manual"
              asn_value: "1900:1900"
              route_target_type: "both"
              state: "present"
          state: "present"
     
          

      vrf:
        - name: DEV
          state: "present"      
          vni: 10000
          adv_ipv4:
           - type: "connected"
             state: "present"
           - type: "bgp"
             state: "present"
          route_target:
           - type: "manual"
             asn_value: "65530:10"
             route_target_type: "both"
             state: "present"
        - name: NET
          state: "present"      
          vni: 11000
          adv_ipv4:
           - type: "connected"
             state: "present"
           - type: "bgp"
             state: "present"
          route_target:
           - type: "manual"
             asn_value: "65530:11"
             route_target_type: "both"
             state: "present"
        - name: APP
          state: "present"      
          vni: 12000
          adv_ipv4:
           - type: "connected"
             state: "present"
           - type: "bgp"
             state: "present"
          route_target:
           - type: "manual"
             asn_value: "65530:12"
             route_target_type: "both"
             state: "present"
        - name: DB
          state: "present"      
          vni: 13000
          adv_ipv4:
           - type: "connected"
             state: "present"
           - type: "bgp"
             state: "present"
          route_target:
           - type: "manual"
             asn_value: "65530:13"
             route_target_type: "both"
             state: "present"
        - name: WEB
          state: "present"      
          vni: 14000
          adv_ipv4:
           - type: "connected"
             state: "present"
           - type: "bgp"
             state: "present"
          route_target:
           - type: "manual"
             asn_value: "65530:14"
             route_target_type: "both"
             state: "present"
     

    dis_rt_asn: "true"

    virtual_network:
      virtual_net:
    
        - id: 1700
          vxlan_vni:
           id: 1700
          state: "present" 
    
        - id: 1800
          vxlan_vni:
           id: 1800
          state: "present" 
    
        - id: 1900
          vxlan_vni:
           id: 1900
          state: "present" 
 
    vlan_association:
    
      - vlan_id: 1700
        virtual_net: 1700
    
      - vlan_id: 1800
        virtual_net: 1800
    
      - vlan_id: 1900
        virtual_net: 1900
 

dellos_vrf:
    vrfdetails:
    
      - vrf_name: DEV 
        state: "present"
    
      - vrf_name: NET 
        state: "present"
    
      - vrf_name: APP 
        state: "present"
    
      - vrf_name: DB 
        state: "present"
    
      - vrf_name: WEB 
        state: "present"
           
        
        
